# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy to Azure Web App

on:
  push:
    branches:
      - master
    paths:
      - app/**
      - models/**
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://ecgclassificationreg.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_e9ede5706fb64937b77b4db1930ef9f8 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_88f7de60243247c1a597232a7b882358 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ecgclassificationreg.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e9ede5706fb64937b77b4db1930ef9f8 }}/mlh-ecg-classification:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ecg-classification'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0a48bb78d2b542f5b5a27777b90576af }}
        images: 'ecgclassificationreg.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e9ede5706fb64937b77b4db1930ef9f8 }}/mlh-ecg-classification:${{ github.sha }}'
